using System;
using System.Configuration;

namespace CoachSeek.Api
{
    /// <summary>
    /// This class was generated by the AppSettings T4 template
    /// </summary>
    public static class AppSettings
    {
        public static string webpages_Version { get { return GetConfigSettingItem("webpages:Version"); } }
        public static string webpages_Enabled { get { return GetConfigSettingItem("webpages:Enabled"); } }
        public static string ClientValidationEnabled { get { return GetConfigSettingItem("ClientValidationEnabled"); } }
        public static string UnobtrusiveJavaScriptEnabled { get { return GetConfigSettingItem("UnobtrusiveJavaScriptEnabled"); } }
        public static string AWSAccessKey { get { return GetConfigSettingItem("AWSAccessKey"); } }
        public static string AWSSecretKey { get { return GetConfigSettingItem("AWSSecretKey"); } }
        public static string AWSRegion { get { return GetConfigSettingItem("AWSRegion"); } }
        public static string EmailSender { get { return GetConfigSettingItem("EmailSender"); } }
        public static string IsEmailingEnabled { get { return GetConfigSettingItem("IsEmailingEnabled"); } }
        //public static string IsPaymentEnabled { get { return GetConfigSettingItem("IsPaymentEnabled"); } }
        public static string AdminUserName { get { return GetConfigSettingItem("AdminUserName"); } }
        public static string AdminPassword { get { return GetConfigSettingItem("AdminPassword"); } }
    
        private const string MISSING_CONFIG = "Invalid configuration. Required AppSettings section is missing";
        private const string INVALID_CONFIG_SETTING = "Invalid configuration setting name: {0}";

        private static string GetConfigSettingItem(string name)
        {
            if (ConfigurationManager.AppSettings == null)
                throw new ConfigurationErrorsException(MISSING_CONFIG);

            string value = null;
            if (ConfigurationManager.AppSettings.Count != 0)
            {
                try
                {
                    value = ConfigurationManager.AppSettings.Get(name);
                }
                catch (Exception exception)
                {
                    throw new ConfigurationErrorsException(SettingItemErrorMessage(name, exception));
                }
            }
            return value;
        }
        
        private static string SettingItemErrorMessage(string name)
        {
            return string.Format(INVALID_CONFIG_SETTING, name);
        }

        private static string SettingItemErrorMessage(string name, Exception exception)
        {
            return string.Format(INVALID_CONFIG_SETTING, name) + exception.Message;
        }
    }
}
